### PR TITLE
Feature/code docs

### PR DESCRIPTION
**Pull request by chiouyazo**
Self explanatory~

### CODE REVIEW

**Comment by kraecktus** [comment]
ticket ref: https://github.com/awaescher/OllamaSharp/issues/8

**Comment by awaescher** [comment]
Please update the summary I commented to above so that I can merge it. Thanks!

**Comment by chiouyazo** [comment]
> Please update the summary I commented to above so that I can merge it. Thanks!

Which comment? I don't see any

**Comment by awaescher** [comment]
Now this is strange to me:

image

**Review by awaescher — CHANGES_REQUESTED** [review]

**Comment by chiouyazo** [comment]
Sorry I was busy with work, I will implement it once I get the time

**Comment by awaescher** [comment]
All good, I merged it 4 days ago and did some editing myself. Thanks!

**Pull request merged**
