### PR TITLE
Add JsonSchema

### PR DESCRIPTION
**Pull request by mili-tan**

### CODE REVIEW

**Comment by awaescher** [comment]
Looks really awesome, but would you elaborate for noobs like me?

**Comment by mili-tan** [comment]
[https://github.com/ollama/ollama/releases/tag/v0.5.0](https://github.com/ollama/ollama/releases/tag/v0.5.0)

Here's some new things added to Ollama 0.5, and maybe something like this:

```
public class Country()
{
	public string Name { get; set; }
	public string Capital { get; set; }
	public List<string> Languages { get; set; }
}

var ollama = new OllamaApiClient("http://localhost:11434");
ollama.SelectedModel = "llama3.1";

await foreach(var res in ollama.GenerateAsync(new GenerateRequest()
         {
	         Prompt = "Tell me about Canada.",
	         Format = JsonSchema.ToJsonSchema(typeof(Country)),
	         Stream = false
         }))
	Console.WriteLine(res.Response);

//{ "Capital": "Ottawa", "Languages": [ "English", "French" ], "Name": "Canada" }
```

**Comment by awaescher** [comment]
Holy moly, I totally missed this announcement. Did you try it successfully yet?

**Comment by mili-tan** [comment]
I think it works, for me.

**Pull request merged**
