### PR TITLE
Added a simpler one-time chat api

### PR DESCRIPTION
**Pull request by Binozo**
Hello 🤠

 I needed a simpler api to one-time chat with my ollama endpoint
Hope it fits well

### CODE REVIEW

**Comment by awaescher** [comment]
Hey Binozo, thanks for helping out. May I ask what the intention is for the changes you added?

**Comment by Binozo** [comment]
In my use case I built a RAG system and need a simple way to chat with a model once, because I got one question and I want one answer. The way through `IAsyncEnumerable<ChatResponseStream?> Chat` was a little confusing for me 😅

**Comment by awaescher** [comment]
Hm, I guess you would have needed `StreamToEnd()` if I understand correctly. This is available as extension method to `IAsyncEnumerable<T>`. See [the announcement of version 3.0](https://github.com/awaescher/OllamaSharp/releases/tag/3.0.0).

**Comment by Binozo** [comment]
Oh I wan't aware of that, thanks for the clarification!

**Pull request closed without merging**
